name: on-push-or-pull

env:
  # set to '1' to enable action cache (perf/saving is negligible, if at all)
  USE_CACHE: 0

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: bun::preheat-cache
        if  : env.USE_CACHE == 1
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key : ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: bun::preheat-oven
        uses: oven-sh/setup-bun@v2
        with:
          # version-opts: latest, canary, <sha>, <ver> (1.2.0)
          bun-version: latest

      # install deps
      - name: make::install
        run : make install

      # the 'make release' target does it all: clean, setup, build, lint, test, aok (the entire jamboree)
      - name: make::release
        run : make release
